apiVersion: v1
kind: ReplicationController
metadata:
  name: tabula-v1.0.0
  namespace: pub
  labels:
    app: tabula
    version: v1.0.0
spec:
  replicas: 1
  selector:
    app: tabula
    version: v1.0.0
  template:
    metadata:
      labels:
        app: tabula
        version: v1.0.0
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      dnsPolicy: Default
